
CREATE TABLE "public"."table1" (
     "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
         INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
     "name" varchar(255) COLLATE "pg_catalog"."default",
     "json" varchar(255) COLLATE "pg_catalog"."default",
     "ref" int8,
     PRIMARY KEY ("id")
);

CREATE TABLE "public"."table2" (
                                   "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                       INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                   "name" varchar(255) COLLATE "pg_catalog"."default",
                                   "age" int8,
                                   "ref" int8,
                                   PRIMARY KEY ("id")
);

CREATE TABLE "public"."table3" (
                                   "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                       INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                   "name" varchar(255) COLLATE "pg_catalog"."default",
                                   "info" varchar(255) COLLATE "pg_catalog"."default",
                                   "ref" int8,
                                   PRIMARY KEY ("id")
);
